[general]
import = [ 
    "~/.config/alacritty/tokyo-night-storm.toml",
    # "~/.config/alacritty/tokyo-night.toml",
]

[window]
decorations = "None" 
# opacity = 0.90
opacity = 1
padding = { x = 20, y = 20 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12
