#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


autostart="/home/kasetonix/.dwm/autostart.sh"
dwm_log="/home/kasetonix/.dwm/err.log"
export DRI_PRIME=0

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

if [ -f "$autostart" ]; then
    $autostart
fi

if [ -f "$dwm_log" ]; then
    echo -e "\n\n" >> $dwm_log 
fi

echo "-=-=-=-=- dwm start -=-=-=-=-" >> $dwm_log 
echo "-=- $(date '+%R:%S | %d/%m/%Y') -=-" >> $dwm_log 

# alias dmenu="dmenu -p '➜ '"
exec dwm 2>> $dwm_log 
