statusbar_format = "%title [%artists]"
notify = true

[keybindings]
"Ctrl+a"   = "focus library"
"Ctrl+s"   = "focus search"
"Ctrl+d"   = "focus queue"
"="        = "volup 5"
"-"        = "voldown 5"
"]"        = "volup 10"
"["        = "voldown 10"
">"        = "next"
"<"        = "previous"
"."        = "seek +10s"
","        = "seek -10s"
"\\"       = "open selected"
"|"        = "open current"
"Space"    = "playpause"
"u"        = "update"
"m"        = "move playing"
"t"        = "shuffle"

# NOOPS
"F1"         = "noop"
"F2"         = "noop"
"F3"         = "noop"
"+"          = "noop"
"Ctrl+l"     = "noop"
"Ctrl+e"     = "noop"
"Ctrl+n"     = "noop"
"Ctrl+p"     = "noop"
"Shift+a"    = "noop"
"Shift+b"    = "noop"
"Shift+f"    = "noop"
"Shift+m"    = "noop"
"Shift+n"    = "noop"
"Shift+o"    = "noop"
"Shift+p"    = "noop"
"Shift+s"    = "noop"
"Shift+x"    = "noop"
"Shift+Up"   = "noop"
"Shift+Down" = "noop"
"a"          = "noop"
"b"          = "noop"
"f"          = "noop"
"h"          = "noop"
"j"          = "noop"
"k"          = "noop"
"l"          = "noop"
"m"          = "noop"
"n"          = "noop"
"o"          = "noop"
"x"          = "noop"
"z"          = "noop"

[theme]
background = "#00262B32"
primary = "#ABB2BF"
secondary = "#98C379"
title = "#98C379"
playing = "#56B6C2"
playing_selected = "#31343F"
playing_bg = "#00262B32"
highlight = "#31343F"
highlight_bg = "#98C379"
error = "#31343F"
error_bg = "#E06C75"
statusbar = "#56B6C2"
statusbar_bg = "#00262B32"
statusbar_progress = "#56B6C2"
cmdline = "#31343F"
cmdline_bg = "#98C379"

[track_format]
left   = "%title"
center = "%artists [%album]"
right  = "[%duration]"

[notification_format]
title  = "%title"
body   = "%artists"

#[notification_format]
#title  = "  %title"
#body   = "  %artists"
