#!/bin/sh

options="Shutdown\nReboot\nExit dwm\nCancel"
action="$(echo -e $options | dmenu -noi -p "System Menu: ")"

case "$action" in
    "Shutdown") doas poweroff;;
    "Reboot") doas reboot;;
    "Exit dwm") pkill dwm;;
    "Cancel") exit 0;;
    *) exit 1;;
esac
