#!/bin/sh

options="Shutdown\nReboot\nExit dwm\nReconfigure\nCancel"
action="$(echo -e $options | dmenu -noi -p "System Menu: ")"

case "$action" in
    "Shutdown") doas poweroff;;
    "Reboot") doas reboot;;
    "Exit dwm") pkill dwm;;
    "Reconfigure") pkill autostart.sh && /home/kasetonix/.dwm/autostart.sh;;
    "Cancel") exit 0;;
    *) exit 1;;
esac
