# Aliases for accesing config files
alias conf-i3='$EDITOR ~/.config/i3/config && cd ~/.config/i3/config'
alias conf-hypr='$EDITOR ~/.config/hypr/hypr.conf && cd ~/.config/hypr/hypr.conf'
alias conf-dwm='$EDITOR ~/.dwm/config.def.h && cd ~/.dwm/config.def.h'
alias conf-alacritty='$EDITOR ~/.config/alacritty/alacritty.yml && cd ~/.config/alacritty/alacritty.yml'
alias conf-kitty='$EDITOR ~/.config/kitty/kitty.conf && cd ~/.config/kitty/kitty.conf'
alias conf-polybar='$EDITOR ~/.config/polybar/config.ini && cd ~/.config/polybar/config.ini'
alias conf-bash='$EDITOR ~/.bashrc && cd ~/.bashrc'
alias conf-fish='$EDITOR ~/.config/fish/ && cd ~/.config/fish/'
alias conf-zsh='$EDITOR ~/.config/zsh/ && cd ~/.config/zsh/'
alias conf-vim='$EDITOR ~/.vimrc && cd ~/.vimrc'
alias conf-nvim='$EDITOR ~/.config/nvim/lua/ && cd ~/.config/nvim/lua/'
alias conf-neofetch='$EDITOR ~/.config/neofetch/config.conf && cd ~/.config/neofetch/config.conf'
alias conf-zathura='$EDITOR ~/.config/zathura/zathurarc && cd ~/.config/zathura/zathurarc'
alias conf-bspwm='$EDITOR ~/.config/bspwm/bspwmrc && cd ~/.config/bspwm/bspwmrc'
alias conf-sxhkd='$EDITOR ~/.config/sxhkd/sxhkdrc && cd ~/.config/sxhkd/sxhkdrc'
alias conf-picom='$EDITOR ~/.config/picom.conf && cd ~/.config/picom.conf'
alias conf-dunst='$EDITOR ~/.config/dunst/dunstrc && cd ~/.config/dunst/dunstrc'
alias conf-syncdot='$EDITOR ~/.scripts/syncdot && cd ~/.scripts/syncdot'
alias conf-ncspot='$EDITOR ~/.config/ncspot/config.toml && cd ~/.config/ncspot/config.toml'
alias conf-mpd='$EDITOR ~/.config/mpd/mpd.conf && cd ~/.config/mpd/mpd.conf'
alias conf-ncmpcpp='$EDITOR ~/.config/ncmpcpp/ && cd ~/.config/ncmpcpp/'
alias conf-vis='$EDITOR ~/.config/vis/config && cd ~/.config/vis/config'
alias conf-ranger='$EDITOR ~/.config/ranger/ && cd ~/.config/ranger/'

FPROFILE='uzjsy4yj.kasetonix'
alias conf-firefox='$EDITOR ~/.mozilla/firefox/$FPROFILE/chrome && cd ~/.mozilla/firefox/$FPROFILE/chrome'

alias catpat='set_color -o yellow; cat /home/kasetonix/docs/gitpat'
