# Aliases for accesing config files
alias conf-i3='$EDITOR ~/.config/i3/config && cd ~/.config/i3/'
alias conf-hypr='$EDITOR ~/.config/hypr/hypr.conf && cd ~/.config/hypr/'
alias conf-dwm='$EDITOR ~/.dwm/config.def.h && cd ~/.dwm/'
alias conf-alacritty='$EDITOR ~/.config/alacritty/ && cd ~/.config/alacritty/'
alias conf-kitty='$EDITOR ~/.config/kitty/kitty.conf && cd ~/.config/kitty/'
alias conf-polybar='$EDITOR ~/.config/polybar/config.ini && cd ~/.config/polybar/'
alias conf-bash='$EDITOR ~/.bashrc && cd ~'
alias conf-fish='$EDITOR ~/.config/fish/ && cd ~/.config/fish/'
alias conf-zsh='$EDITOR ~/.config/zsh/ && cd ~/.config/zsh/'
alias conf-vim='$EDITOR ~/.vimrc && cd ~'
alias conf-nvim='$EDITOR ~/.config/nvim/lua/ && cd ~/.config/nvim/lua/'
alias conf-neofetch='$EDITOR ~/.config/neofetch/config.conf && cd ~/.config/neofetch/'
alias conf-zathura='$EDITOR ~/.config/zathura/zathurarc && cd ~/.config/zathura/'
alias conf-bspwm='$EDITOR ~/.config/bspwm/bspwmrc && cd ~/.config/bspwm/'
alias conf-sxhkd='$EDITOR ~/.config/sxhkd/sxhkdrc && cd ~/.config/sxhkd/'
alias conf-picom='$EDITOR ~/.config/picom.conf && cd ~/.config/'
alias conf-dunst='$EDITOR ~/.config/dunst/dunstrc && cd ~/.config/dunst/'
alias conf-syncdot='$EDITOR ~/.scripts/syncdot && cd ~/.scripts/'
alias conf-ncspot='$EDITOR ~/.config/ncspot/config.toml && cd ~/.config/ncspot/'
alias conf-mpd='$EDITOR ~/.config/mpd/mpd.conf && cd ~/.config/mpd/'
alias conf-ncmpcpp='$EDITOR ~/.config/ncmpcpp/ && cd ~/.config/ncmpcpp/'
alias conf-vis='$EDITOR ~/.config/vis/config && cd ~/.config/vis/'
alias conf-ranger='$EDITOR ~/.config/ranger/ && cd ~/.config/ranger/'

FPROFILE='uzjsy4yj.kasetonix'
alias conf-firefox='$EDITOR ~/.mozilla/firefox/$FPROFILE/chrome && cd ~/.mozilla/firefox/$FPROFILE/chrome'

alias catpat='echo "$fg_bold[yellow]$(cat /home/kasetonix/docs/gitpat)"'
