# Aliases for accesing config files
# alias conf-portage='cd /etc/portage && doas $EDITOR /etc/portage/make.conf'
# alias conf-i3='cd ~/.config/i3/ && $EDITOR ~/.config/i3/config'
# alias conf-hypr='cd ~/.config/hypr/ && $EDITOR ~/.config/hypr/hypr.conf'
alias conf-dwm='cd ~/.dwm/ && $EDITOR ~/.dwm/config.def.h'
alias conf-dmenu='cd ~/.dmenu/ && $EDITOR ~/.dmenu/config.def.h'
alias conf-st='cd ~/.st/ && $EDITOR ~/.st/config.def.h'
# alias conf-alacritty='cd ~/.config/alacritty/ && $EDITOR ~/.config/alacritty/'
# alias conf-kitty='cd ~/.config/kitty/ && $EDITOR ~/.config/kitty/kitty.conf'
# alias conf-polybar='cd ~/.config/polybar/ && $EDITOR ~/.config/polybar/config.ini'
# alias conf-bash='cd ~ && $EDITOR ~/.bashrc'
# alias conf-fish='cd ~/.config/fish/ && $EDITOR ~/.config/fish/'
alias conf-zsh='cd ~/.config/zsh/ && $EDITOR ~/.config/zsh/'
# alias conf-vim='cd ~ && $EDITOR ~/.vimrc'
alias conf-nvim='cd ~/.config/nvim/lua/ && $EDITOR ~/.config/nvim/lua/'
alias conf-neofetch='cd ~/.config/neofetch/ && $EDITOR ~/.config/neofetch/config.conf'
# alias conf-zathura='cd ~/.config/zathura/ && $EDITOR ~/.config/zathura/zathurarc'
# alias conf-bspwm='cd ~/.config/bspwm/ && $EDITOR ~/.config/bspwm/bspwmrc'
# alias conf-sxhkd='cd ~/.config/sxhkd/ && $EDITOR ~/.config/sxhkd/sxhkdrc'
alias conf-picom='cd ~/.config/ && $EDITOR ~/.config/picom.conf'
alias conf-dunst='cd ~/.config/dunst/ && $EDITOR ~/.config/dunst/dunstrc'
alias conf-syncdot='cd ~/.scripts/ && $EDITOR ~/.scripts/syncdot'
alias conf-ncspot='cd ~/.config/ncspot/ && $EDITOR ~/.config/ncspot/config.toml'
# alias conf-mpd='cd ~/.config/mpd/ && $EDITOR ~/.config/mpd/mpd.conf'
# alias conf-ncmpcpp='cd ~/.config/ncmpcpp/ && $EDITOR ~/.config/ncmpcpp/'
# alias conf-vis='cd ~/.config/vis/ && $EDITOR ~/.config/vis/config'
alias conf-ranger='cd ~/.config/ranger/ && $EDITOR ~/.config/ranger/'

FPROFILE='kasetonix'
alias conf-firefox='cd ~/.mozilla/firefox/$FPROFILE/chrome && $EDITOR ~/.mozilla/firefox/$FPROFILE/chrome'

alias catpat='echo "$fg_bold[yellow]$(cat /home/kasetonix/docs/gitpat)"'
